### PR TITLE
feat: add ZTVI in U.S.A.

### PR DESCRIPTION
**Pull request by GoetzGoerisch**
Acked-by: @buraglio

### CODE REVIEW

**Review by buraglio — CHANGES_REQUESTED** [review]
minor nit ZTVI and not "Ztvi"

**Review by buraglio — CHANGES_REQUESTED** [review]
Adjust case on ZTVI

**Comment by GoetzGoerisch** [comment]
Fixed.

**Review by buraglio — APPROVED** [review]
Looks good!

**Comment by GoetzGoerisch** [comment]
Ping @netaviator

**Pull request merged**
